image: python:latest

services:
    - postgres:latest

variables:
    POSTGRES_DB: nice_marmot
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: "test"

stages:
    - test
    - deploy

test:
    stage: test
    script:
    #Setting-up
    - export DATABASE_URL=postgres://runner:test@postgres/nice_marmot
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    #Run tests with
    - pytest

deploy:
    stage: deploy
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/cianobot.git
        - git push heroku master
        - echo "Deployed to Production Server https://t.me/cianostavernabot"
    environment:
        name: production
        url: https://t.me/cianostavernabot
    when: manual
    only:
        - master
