image: python:latest

stages:
    - test
    - deploy

test:
    stage: test
    script:
    #Setting-up
    - export DATABASE_URL=postgres://eyicwwxwnxuxou:675f943b8955a12022eab26b184c193d3c1219c4999688d899cfb3687f33e1b4@ec2-54-217-234-157.eu-west-1.compute.amazonaws.com:5432/df8fia9ccanh45
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    #Run tests with
    - pytest