image: python:latest

stages:
    - test
    - deploy

test:
    stage: test
    script:
    #Setting-up
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    #Run tests with
    - pytest

deploy:
    stage: deploy
    script:
        - gem install dpl
        - dpl --provider=heroku --app=cianobot --api-key=$HEROKU_API_KEY
        - echo "Deployed to Production Server https://t.me/cianostavernabot"
    environment:
        name: production
        url: https://t.me/cianostavernabot
    when: manual
    only:
        - master
