image: python:latest

stages:
    - test
    - deploy

test:
    stage: test
    script:
    #Setting-up
    - export DATABASE_URL= postgres://kztdqvcvabikuw:558e67b9ac1b55d22d94a8790b5bde3918d69e89e20f136cf89e25fdbc8d39e4@ec2-54-220-0-91.eu-west-1.compute.amazonaws.com:5432/d1q4vs74un4gp1
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    #Run tests with
    - pytest
